### ISSUE TITLE
Hypnotoad won't start because of method 'bridge' not found

### ISSUE THREAD

**Issue by verhage** [OPMDG/opm-doc#3] opened 2015-03-04 16:50 UTC
Don't know if this is a documentation issue though. I followed the documentation, but when starting "hypnotoad /usr/local/src/opm/opm-core-master/ui/script/opm", I get the following error:

Can't load application from file "/usr/local/src/opm/opm-core-master/ui/script/opm": Can't locate object method "bridge" via package "Mojolicious::Routes" at /usr/local/src/opm/opm-core-master/ui/script/../lib/OPM.pm line 103.

**Comment by rjuju** [comment] 2015-03-04 17:17
Hello,

Thanks for the report. It's an issue caused by the new 6.0 release of mojolicious, released 6 days ago.

For now, OPM 2.3 is only compatible with mojolicious versions between 4.50 and 4.99 (see https://github.com/OPMDG/opm-doc/blob/master/opm-core/Installation.rst).

Some recent patches on opm-core and opm-wh_nagios fixed incompatibilities with mojo 5.0+, but it's not released yes, and there hasn't been any work for mojo 6.0+ for now.

Therefore, you should consider using Mojolicious 4.99 with OPM 2.3

Regards.

**Comment by verhage** [comment] 2015-03-04 21:30
Ah, ok. I'm new to Mojolicious. I figured out how to install the i18n plugin: 

    cpan Mojolicious::Plugin::I18N

But this fails due to a check for Mojolicious 5.0. How do I install the correct plugin version?

**Comment by verhage** [comment] 2015-03-04 21:54
Ok, got it running now, figured out how to install Mojolicious with required dependencies:

    curl -L cpanmin.us | perl - Mojolicious@4.99
    wget http://search.cpan.org/CPAN/authors/id/S/SH/SHARIFULN/Mojolicious-Plugin-I18N-1.21.tar.gz
    tar -xzf Mojolicious-Plugin-I18N-1.21.tar.gz
    cd Mojolicious-Plugin-I18N-1.21
    perl Makefile.PL && make install
    perl -MCPAN -e 'install DBI'

Might be a good idea to add this to the documentation for Mojolicious (and Perl) newbies like me ;)

**Closed** 2015-03-05 19:18 UTC

**Comment by rjuju** [comment] 2015-03-05 19:20
I just add some clarification and example to help Mojolicious and Mojolicious::Plugin::I18N installation based on you example.

Thank you !

**Comment by verhage** [comment] 2015-03-06 16:22
Glad to help, you should also add

    RUN curl -L cpanmin.us | perl - DBI
    RUN curl -L cpanmin.us | perl - DBD::Pg

for completeness :)

**Comment by rjuju** [comment] 2015-07-28 11:27
For the record, it has been added in commit 94dc62220b902a8a879b4159cc5b16d4bb320c63.

Thanks again!

**Comment by ernestoarbitrio** [comment] 2015-09-16 08:41
i've tried all your steps but i always have the same error
<code>Can't load application from file "/usr/local/src/opm/opm-core-REL_2_3/ui/script/opm": Can't locate object method "bridge" via package "Mojolicious::Routes" at /usr/local/src/opm/opm-core-REL_2_3/ui/script/../lib/OPM.pm line 103.
Compilation failed in require at (eval 41) line 1.</code>

can help me? thanks

**Comment by rjuju** [comment] 2015-09-16 10:09
For some reason, a too recent version of mojolicious is found.
Did you try to install mojolicious 4.99 with 

    curl -L cpanmin.us | perl - Mojolicious@4.99
    curl -L cpanmin.us | perl - Mojolicious::Plugin::I18N@0.9

Also, did you uninstall previous mojolicious package ?
